server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studies?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: leop@77
  jpa:
    hibernate:
      ddl-auto: update
logging:
    level:
        org:
          hibernate:
              SQL: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
